trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: AccuKnox-container-scan@0
    inputs:
      dockerfile: $(dockerfile)
      imageName: ${imageName)
      accuknoxEndpoint: $(accuknoxEndpoint)
      accuknoxTenantId: $(accuknoxTenantId)
      accuknoxToken: $(accuknoxToken)
      accuknoxLabel: $(accuknoxLabel)
      qualityGate: $(qualityGate)
