name: AccuKnox Scan Workflow

trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

variables:
  dockerfile_context: 'Dockerfile'
  endpoint: 'cspm.dev.accuknox.com'
  token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxMjEzNjc3LCJqdGkiOiIxMTdlM2VhNmQxZjA0ZmFkYjFiNDQ2ZWNhZGVlY2MzNCIsImlzcyI6ImNzcG0uZGVtby5hY2N1a25veC5jb20ifQ.IZ1TY2mEWSaCXwDp6XTVffTdJ6GvYMfTO5iseQ8sjrd2olXWbcptSYGeRDHPkF9ufW5hVkuwLAT6Q0AsmgzHmwUzLa-0ILuo0XrN8MFPPC4J1Ao8_2v28GsCGTM8vUFkemesSdJh1Q40FGDxHD4TNNo7YRTZwpOMx36TSod4H1Bxb0xqtOYbeYW7xkB8rrHQ11snx4c7q-Emjzaq3yMvhcMS4X5-OurTQvDzNEQeo-eoz07gV4FNA8ipQgM275IMt-M5CmaSAPuvUVWCsQ1227bs-6S8bDHBOKL1HHYHJADVibbgCY8tOz6IhpabrIGK8CTfuRIWHhW-M4GhvkwiTw'
  tenant_id: '167'
  repository_name: 'udit-uniyal/accuknox-container-scan-example'
  tag: 'latest'
  severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
  exit_code: '0'

jobs:
  - job: accuknox_cicd
    displayName: AccuKnox CI/CD
    pool:
      name: 'ubuntu'

    steps:
      - checkout: self
      
      - script: |
          echo "Validating Inputs"
          curl -o validate_inputs.py https://raw.githubusercontent.com/accuknox/container-scan-action/main/validate_inputs.py
          python validate_inputs.py
        displayName: 'Validate Inputs'
        env:
          DOCKERFILE_CONTEXT: $(dockerfile_context)
          ENDPOINT: $(endpoint)
          TOKEN: $(token)
          TENANT_ID: $(tenant_id)
          REPOSITORY_NAME: $(repository_name)
          TAG: $(tag)
          SEVERITY: $(severity)
          CODE: $(exit_code)

      - script: |
          echo "Building Docker Image"
          docker build -t $(repository_name):$(tag) -f $(DOCKERFILE_CONTEXT) .
        displayName: 'Docker Build'
      
      - script: |
          echo "Downloading Vulnerability Scanner"
          sudo curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin > /dev/null
        displayName: 'Download Vulnerability Scanner'
      
      - script: |
          echo "Running AccuKnox Vulnerability Scanner"
          sudo trivy image --severity $(severity) -f json $(repository_name):$(tag) -o results.json --quiet 
        displayName: 'Run AccuKnox Vulnerability Scanner'
      
      - script: |
          echo "Printing AccuKnox Results"
          cat results.json
        displayName: 'Print AccuKnox Results'

      - script: |
          echo "Pushing Report to CSPM Panel"
          curl --location --request POST 'https://$(endpoint)/api/v1/artifact/?tenant_id=$(tenant_id)&data_type=TR&save_to_s3=false' --header 'Tenant-Id: $(tenant_id)' --header 'Authorization: Bearer $(token)' --form 'file=@"./results.json"'
        displayName: 'Push Report to CSPM Panel'

      - script: |
          echo "Running AccuKnox Vulnerability Scanner with Specific Tags"
          trivy image --exit-code $(exit_code) --severity $(severity) $(repository_name):$(tag) --quiet >/dev/null
        displayName: 'Run AccuKnox Vulnerability Scanner with Specific Tags'
